version: '3'

services:

  web: 
    build: .
    command: uvicorn core.main:app --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/user/src/app
    ports:
      - 8004:8000
    env_file:
      - ./.env
